Playing with benchmarks script

diff --git a/.github/workflows/LINUX_BUILD_TEST.yml b/.github/workflows/LINUX_BUILD_TEST.yml
--- a/.github/workflows/LINUX_BUILD_TEST.yml
+++ b/.github/workflows/LINUX_BUILD_TEST.yml
@@ -26,8 +26,8 @@ jobs:
       fail-fast: false
       matrix:
         
-        COMPILER: ['gcc-7']# , 'gcc-8', 'gcc-9', 'gcc-10'] # armclang ] compiler names
-        OS: ['ubuntu:18.04']#,'ubuntu:20.04', 'rockylinux:8', 'redhat/ubi8:latest', 'redhat/ubi9:latest', 'debian:10', 'debian:11'] # Docker images
+        COMPILER: ['gcc-7', 'gcc-8', 'gcc-9', 'gcc-10'] # armclang ] compiler names
+        OS: ['ubuntu:18.04','ubuntu:20.04', 'rockylinux:8', 'redhat/ubi8:latest', 'redhat/ubi9:latest', 'debian:10', 'debian:11'] # Docker images
         
         #######################################
         # Removes unecessary jobs as jobs are generated in the order seen in the matrix.
@@ -177,11 +177,16 @@ jobs:
 
       - if: ${{ inputs.SIMENG-MODE == 'Release' }}
         name: CloverLeaf serial gcc8.3.0 armv8.4
-        uses: ./.github/actions/simeng_benchmarks
-        with:
-          RUN_DIR: $GITHUB_WORKSPACE/simeng-benchmarks/Data_Files/CloverLeaf
-          BIN_PATH: $GITHUB_WORKSPACE/simeng-benchmarks/binaries/CloverLeaf/serial/cloverleaf_gcc8.3.0_armv8.4
-          PASS_STRING: "This test is considered PASSED"
+        run:
+          cd $GITHUB_WORKSPACE/simeng-benchmarks/Data_Files/CloverLeaf
+          simeng $GITHUB_WORKSPACE/configs/a64fx.yaml $GITHUB_WORKSPACE/simeng-benchmarks/binaries/CloverLeaf/serial/cloverleaf_gcc8.3.0_armv8.4 2>&1 tee $GITHUB_WORKSPACE/simeng.tmp
+          STRING_FOUND=$(grep "This test is considered PASSED" $GITHUB_WORKSPACE/simeng.tmp)
+          if $STRING_FOUND; then
+            echo "Passed"
+          else
+            echo "Failed"
+            exit 1
+          fi
 
 
 #      - if: ${{ inputs.SIMENG-MODE == 'Release' }}
